import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

const tempStoreDir = fs.mkdtempSync(path.join(os.tmpdir(), "hardware-flow-pilot-store-"));
process.env.HARDWARE_FLOW_STORE_PATH = path.join(tempStoreDir, "store.json");
process.env.HARDWARE_FLOW_ACCESS_LOG = "0";

const { preparePilotArchive } = await import("./pilotArchive.mjs");

test("pilot archive writes review, risk, runtime, and import artifacts", () => {
  const outputDir = fs.mkdtempSync(path.join(os.tmpdir(), "hardware-flow-pilot-archive-"));

  const result = preparePilotArchive(outputDir);
  const manifestPath = path.join(outputDir, "pilot-archive-manifest.json");
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));

  assert.equal(result.outputDir, outputDir);
  assert.equal(result.manifestPath, manifestPath);
  assert.equal(typeof manifest.project.id, "string");
  assert.equal(manifest.project.id.length > 0, true);
  assert.equal(manifest.readiness.storageValid, true);
  assert.equal(manifest.readiness.postgresImportValid, true);
  assert.equal(manifest.readiness.checklistRequiredTotal > 0, true);
  assert.equal(manifest.files.handoffMarkdown, "pilot-handoff.md");
  assert.equal(manifest.files.briefMarkdown, "pilot-brief.md");
  assert.equal(manifest.files.pilotLaunchJson, "pilot-launch-summary.json");
  assert.equal(manifest.files.snapshotJson, "project-snapshot.json");
  assert.equal(manifest.files.riskRegisterMarkdown, "risk-register.md");
  assert.equal(manifest.files.gateReviewPackMarkdown, "gate-review-pack.md");
  assert.equal(manifest.files.pilotReadinessJson, "pilot-readiness.json");
  assert.equal(manifest.files.pilotChecklistJson, "pilot-checklist.json");
  assert.equal(manifest.files.opsSummaryJson, "ops-summary.json");
  assert.equal(manifest.files.issueReportMarkdown, "pilot-issue-report.md");
  assert.equal(manifest.files.rollbackCardMarkdown, "pilot-rollback-card.md");
  assert.equal(manifest.files.deploymentDrillMarkdown, "pilot-deployment-drill.md");
  assert.equal(manifest.files.deploymentDrillJson, "pilot-deployment-drill.json");
  assert.equal(manifest.files.feedbackLedgerMarkdown, "pilot-feedback-ledger.md");
  assert.equal(manifest.files.feedbackLedgerJson, "pilot-feedback-ledger.json");
  assert.equal(manifest.files.m7BacklogMarkdown, "pilot-m7-backlog.md");
  assert.equal(manifest.files.m7BacklogJson, "pilot-m7-backlog.json");
  assert.equal(manifest.files.trialScopeMarkdown, "pilot-trial-scope.md");
  assert.equal(manifest.files.trialScopeJson, "pilot-trial-scope.json");
  assert.equal(manifest.files.opsAlertsMarkdown, "pilot-ops-alerts.md");
  assert.equal(manifest.files.opsAlertsJson, "pilot-ops-alerts.json");
  assert.equal(manifest.files.archiveIndexMarkdown, "pilot-archive-index.md");
  assert.equal(manifest.files.archiveIndexJson, "pilot-archive-index.json");
  assert.equal(manifest.files.handoffWalkthroughMarkdown, "pilot-handoff-walkthrough.md");
  assert.equal(manifest.files.handoffWalkthroughJson, "pilot-handoff-walkthrough.json");
  assert.equal(manifest.files.m6CloseoutMarkdown, "pilot-m6-closeout.md");
  assert.equal(manifest.files.m6CloseoutJson, "pilot-m6-closeout.json");
  assert.equal(manifest.files.testPlanMarkdown, "pilot-test-plan.md");
  assert.equal(manifest.files.testPlanJson, "pilot-test-plan.json");
  assert.equal(manifest.readiness.opsSummaryReady, true);
  assert.equal(typeof manifest.operations.blockerCount, "number");
  assert.equal(typeof manifest.operations.warningCount, "number");
  assert.equal(typeof manifest.operations.httpServerErrors, "number");
  assert.equal(typeof manifest.operations.httpClientErrors, "number");
  assert.equal(manifest.operations.storageReady, true);
  assert.equal(typeof manifest.operations.networkReady, "boolean");
  assert.equal(Array.isArray(manifest.operations.nextActions), true);
  assert.equal(manifest.launch.decision, "GO_WITH_CAUTION");
  assert.equal(manifest.launch.canStart, true);
  assert.equal(manifest.launch.requiredPending > 0, true);
  assert.equal(manifest.commands.check, "npm run pilot:check");
  assert.equal(manifest.commands.rehearse, "npm run pilot:rehearse");
  assert.equal(manifest.commands.archive, "npm run pilot:archive -- /tmp/hardware-flow-pilot-archive");
  assert.equal(Array.isArray(manifest.acceptanceCriteria), true);
  assert.equal(manifest.acceptanceCriteria.some((item) => item.includes("工作包生成")), true);
  assert.equal(manifest.acceptanceCriteria.some((item) => item.includes("npm run pilot:check")), true);
  assert.equal(Array.isArray(manifest.runbookSteps), true);
  assert.equal(manifest.runbookSteps.some((item) => item.includes("创建一个试点项目")), true);
  assert.equal(manifest.runbookSteps.some((item) => item.includes("导出项目快照")), true);
  assert.equal(Array.isArray(manifest.boundaries), true);
  assert.equal(manifest.boundaries.some((item) => item.includes("用户登录")), true);
  assert.equal(manifest.boundaries.some((item) => item.includes("PostgreSQL 运行时读写")), true);
  assert.equal(manifest.issueReport.templatePath, "pilot-issue-report.md");
  assert.equal(manifest.issueReport.requiredFields.includes("请求 ID"), true);
  assert.equal(manifest.issueReport.requiredFields.includes("是否需要回滚"), true);
  assert.match(manifest.issueReport.severityGuide, /S1/);
  assert.equal(manifest.rollbackCard.templatePath, "pilot-rollback-card.md");
  assert.equal(manifest.rollbackCard.steps.some((item) => item.includes("恢复检查点")), true);
  assert.equal(manifest.rollbackCard.requiredEvidence.includes("/pilot/launch 结果"), true);
  assert.equal(manifest.deploymentDrill.defaultRuntimeSource, "json");
  assert.equal(manifest.deploymentDrill.postgresDefaultPolicy, "migration_verification_only");
  assert.equal(manifest.deploymentDrill.steps.some((item) => item.key === "start_lan"), true);
  assert.equal(manifest.deploymentDrill.requiredEvidence.includes("/runtime/network 结果"), true);
  assert.equal(manifest.feedbackLedger.templatePath, "pilot-feedback-ledger.md");
  assert.equal(manifest.feedbackLedger.fields.includes("后续节点"), true);
  assert.equal(manifest.feedbackLedger.categories.includes("流程适配"), true);
  assert.equal(manifest.feedbackLedger.priorities.includes("P0"), true);
  assert.equal(manifest.feedbackLedger.statuses.includes("OPEN"), true);
  assert.equal(manifest.feedbackLedger.defaultMilestone, "M7");
  assert.equal(manifest.feedbackLedger.triage.priorityLanes.P0.decision, "FIX_BEFORE_NEXT_PILOT");
  assert.equal(manifest.feedbackLedger.triage.statusTransitions.OPEN.next.includes("TRIAGED"), true);
  assert.equal(manifest.feedbackLedger.triage.readyForPlanningCriteria.includes("负责人已明确"), true);
  assert.equal(manifest.feedbackLedger.m7Backlog.itemFields.includes("验收证据"), true);
  assert.equal(manifest.feedbackLedger.m7Backlog.defaultBuckets.some((item) => item.key === "stability"), true);
  assert.equal(manifest.m7Backlog.milestone, "M7");
  assert.equal(manifest.m7Backlog.itemFields.includes("验收证据"), true);
  assert.equal(manifest.m7Backlog.links.feedbackTriage, "/pilot/feedback-triage");
  assert.equal(manifest.trialScope.templatePath, "pilot-trial-scope.md");
  assert.equal(manifest.trialScope.participantRange, "4-8");
  assert.equal(manifest.trialScope.defaultRuntimeSource, "json");
  assert.equal(manifest.trialScope.postgresPolicy, "migration_verification_only");
  assert.equal(manifest.trialScope.roles.includes("项目经理"), true);
  assert.equal(manifest.trialScope.excludedScopes.includes("生产级 TLS、反向代理、数据库备份和灾备"), true);
  assert.equal(manifest.opsAlerts.templatePath, "pilot-ops-alerts.md");
  assert.equal(manifest.opsAlerts.watchEndpoints.includes("/ops/summary"), true);
  assert.equal(manifest.opsAlerts.watchEndpoints.includes("/metrics"), true);
  assert.equal(manifest.opsAlerts.rules.some((item) => item.code === "READY_DOWN"), true);
  assert.equal(manifest.opsAlerts.rules.some((item) => item.metric === "hardware_flow_http_5xx_total"), true);
  assert.equal(manifest.opsAlerts.escalation.includes("S1"), true);
  assert.equal(manifest.archiveIndex.templatePath, "pilot-archive-index.md");
  assert.equal(manifest.archiveIndex.primaryReadOrder[0].file, "pilot-trial-scope.md");
  assert.equal(manifest.archiveIndex.primaryReadOrder.some((item) => item.file === "pilot-deployment-drill.md"), true);
  assert.equal(manifest.archiveIndex.primaryReadOrder.some((item) => item.file === "pilot-handoff-walkthrough.md"), true);
  assert.equal(manifest.archiveIndex.primaryReadOrder.some((item) => item.file === "pilot-m6-closeout.md"), true);
  assert.equal(manifest.archiveIndex.bySituation.some((item) => item.situation === "现场报错"), true);
  assert.equal(manifest.archiveIndex.bySituation.some((item) => item.files.includes("pilot-rollback-card.md")), true);
  assert.equal(manifest.archiveIndex.bySituation.some((item) => item.situation === "交接走查"), true);
  assert.equal(manifest.archiveIndex.bySituation.some((item) => item.files.includes("pilot-m6-closeout.md")), true);
  assert.equal(manifest.archiveIndex.bySituation.some((item) => item.situation === "会后复盘" && item.files.includes("pilot-m7-backlog.md")), true);
  assert.equal(manifest.handoffWalkthrough.templatePath, "pilot-handoff-walkthrough.md");
  assert.equal(manifest.handoffWalkthrough.steps[0].key, "open_archive_index");
  assert.equal(manifest.handoffWalkthrough.steps.some((item) => item.key === "simulate_incident"), true);
  assert.equal(manifest.handoffWalkthrough.steps.some((item) => item.files.includes("pilot-feedback-ledger.md")), true);
  assert.equal(manifest.handoffWalkthrough.steps.some((item) => item.files.includes("pilot-m7-backlog.md")), true);
  assert.equal(manifest.handoffWalkthrough.requiredEvidence.includes("走查主持人"), true);
  assert.equal(manifest.m6Closeout.templatePath, "pilot-m6-closeout.md");
  assert.equal(manifest.m6Closeout.criteria.some((item) => item.key === "archive_complete"), true);
  assert.equal(manifest.m6Closeout.criteria.some((item) => item.key === "operator_walkthrough"), true);
  assert.equal(manifest.m6Closeout.criteria.some((item) => item.key === "rollback_ready"), true);
  assert.equal(manifest.m6Closeout.remainingDecisions.includes("内部试点的首批用户范围"), true);
  assert.equal(manifest.testPlan.templatePath, "pilot-test-plan.md");
  assert.equal(manifest.testPlan.environment.clientCount, "2-3");
  assert.equal(manifest.testPlan.releaseCriteria.includes("npm run pilot:check 执行成功"), true);
  assert.equal(manifest.testPlan.suites.some((item) => item.key === "lan_startup"), true);
  assert.equal(manifest.testPlan.suites.some((item) => item.key === "core_workflow"), true);
  assert.equal(manifest.testPlan.defectLevels.S1.includes("数据损坏"), true);
  assert.equal(manifest.archiveIndex.primaryReadOrder.some((item) => item.file === "pilot-test-plan.md"), true);
  assert.equal(manifest.archiveIndex.bySituation.some((item) => item.situation === "测试执行" && item.files.includes("pilot-test-plan.md")), true);
  assert.equal(manifest.dataProtection.storePath, process.env.HARDWARE_FLOW_STORE_PATH);
  assert.ok(manifest.dataProtection.backupPath.endsWith("store.json.bak"));
  assert.equal(manifest.dataProtection.storeDoctorCommand, "npm run store:doctor");
  assert.equal(manifest.dataProtection.restoreBackupCommand, "npm run store:restore-backup");
  assert.equal(Array.isArray(manifest.checklist.requiredPending), true);
  assert.equal(manifest.checklist.requiredPending.some((item) => item.key === "checkpoint"), true);
  assert.equal(manifest.checklist.requiredPending.every((item) => item.title && item.action), true);
  assert.equal(manifest.diagnostics.readiness, "/pilot/readiness");
  assert.equal(manifest.diagnostics.launch, "/pilot/launch");
  assert.equal(manifest.diagnostics.feedbackPlan, "/pilot/feedback-plan");
  assert.equal(manifest.diagnostics.feedbackTriage, "/pilot/feedback-triage");
  assert.equal(manifest.diagnostics.m7Readiness, "/pilot/m7-readiness");
  assert.equal(manifest.diagnostics.m7Backlog, "/pilot/m7-backlog");
  assert.equal(manifest.diagnostics.m7BacklogMarkdown, "/pilot/m7-backlog.md");
  assert.equal(manifest.diagnostics.opsSummary, "/ops/summary");
  assert.equal(manifest.diagnostics.metrics, "/metrics");
  assert.equal(manifest.diagnostics.storageStatus, "/storage/status");
  assert.equal(manifest.diagnostics.storageDoctor, "/storage/doctor");
  assert.equal(manifest.postgresImport.manifestPath, "postgres-import/postgres-import-manifest.json");
  assert.equal(manifest.postgresImport.psql.requiredEnv, "DATABASE_URL");
  assert.equal(manifest.postgresImport.psql.createSchema, "psql \"$DATABASE_URL\" -f schemas/database.sql");
  assert.equal(
    manifest.postgresImport.psql.importSeed,
    `psql "$DATABASE_URL" -f ${path.join(outputDir, "postgres-import", "postgres-seed.sql")}`,
  );
  assert.equal(
    manifest.postgresImport.commands.preview,
    `npm run db:import -- ${path.join(outputDir, "postgres-import")}`,
  );
  assert.equal(
    manifest.postgresImport.commands.execute,
    `npm run db:import -- ${path.join(outputDir, "postgres-import")} --confirm`,
  );
  assert.equal(manifest.postgresImport.resultReportPath, "postgres-import/postgres-import-result.json");
  assert.equal(
    manifest.postgresImport.commands.verifyResult,
    `npm run db:verify-import-result -- ${path.join(outputDir, "postgres-import", "postgres-import-result.json")}`,
  );
  assert.equal(
    manifest.postgresImport.commands.restoreStorePreview,
    `npm run db:restore-store -- ${path.join(outputDir, "postgres-import", "postgres-rows.json")}`,
  );
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.snapshotJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.handoffMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.briefMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.pilotLaunchJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.gateReviewPackMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.pilotReadinessJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.pilotChecklistJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.opsSummaryJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.issueReportMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.rollbackCardMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.deploymentDrillMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.deploymentDrillJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.feedbackLedgerMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.feedbackLedgerJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.m7BacklogMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.m7BacklogJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.trialScopeMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.trialScopeJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.opsAlertsMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.opsAlertsJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.archiveIndexMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.archiveIndexJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.handoffWalkthroughMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.handoffWalkthroughJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.m6CloseoutMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.m6CloseoutJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.testPlanMarkdown)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.files.testPlanJson)), true);
  assert.equal(fs.existsSync(path.join(outputDir, manifest.postgresImport.manifestPath)), true);
  assert.equal(JSON.parse(fs.readFileSync(path.join(outputDir, manifest.files.opsSummaryJson), "utf8")).pilot.links.metrics, "/metrics");
  const handoffMarkdown = fs.readFileSync(path.join(outputDir, "pilot-handoff.md"), "utf8");
  assert.match(handoffMarkdown, /内部试点交接页/);
  assert.match(handoffMarkdown, /\/ops\/summary/);
  assert.match(handoffMarkdown, /试点命令/);
  assert.match(handoffMarkdown, /npm run pilot:rehearse/);
  assert.match(handoffMarkdown, /数据保护和回滚/);
  assert.match(handoffMarkdown, /npm run store:doctor/);
  assert.match(handoffMarkdown, /npm run store:restore-backup/);
  assert.match(handoffMarkdown, /试点问题上报/);
  assert.match(handoffMarkdown, /pilot-issue-report\.md/);
  assert.match(handoffMarkdown, /请求 ID/);
  assert.match(handoffMarkdown, /第一轮验收标准/);
  assert.match(handoffMarkdown, /参与者可以独立完成工作包生成、审核、风险处理和阶段门批准/);
  assert.match(handoffMarkdown, /npm run pilot:check 通过，且 \/ready 返回 200/);
  assert.match(handoffMarkdown, /建议试点流程/);
  assert.match(handoffMarkdown, /创建一个试点项目/);
  assert.match(handoffMarkdown, /导出项目快照 JSON 和 Markdown/);
  assert.match(handoffMarkdown, /第一轮试点边界/);
  assert.match(handoffMarkdown, /用户登录和单点登录不作为第一轮内部试点验收项/);
  assert.match(handoffMarkdown, /原生 PostgreSQL 运行时读写不作为第一轮内部试点验收项/);
  assert.match(handoffMarkdown, /PostgreSQL 导入包/);
  assert.match(handoffMarkdown, /未完成必需项/);
  assert.match(handoffMarkdown, /试点前创建数据检查点/);
  assert.match(handoffMarkdown, /下一步：项目 -> 本地数据状态 -> 创建检查点/);
  assert.match(handoffMarkdown, /postgres-import\/postgres-import-manifest\.json/);
  assert.match(handoffMarkdown, /表计数：/);
  assert.match(handoffMarkdown, /一次性命令：`psql "\$DATABASE_URL" -f schemas\/database\.sql && psql "\$DATABASE_URL" -f /);
  assert.match(handoffMarkdown, /受控预览：`npm run db:import -- /);
  assert.match(handoffMarkdown, /受控导入：`npm run db:import -- .* --confirm`/);
  assert.match(handoffMarkdown, /结果报告：`postgres-import\/postgres-import-result\.json`/);
  assert.match(handoffMarkdown, /结果复核：`npm run db:verify-import-result -- /);
  assert.match(handoffMarkdown, /Store 恢复预览：`npm run db:restore-store -- /);
  assert.match(handoffMarkdown, /Store 恢复执行：`npm run db:restore-store -- .* --confirm`/);
  const briefMarkdown = fs.readFileSync(path.join(outputDir, "pilot-brief.md"), "utf8");
  assert.match(briefMarkdown, /内部试点现场简报/);
  assert.match(briefMarkdown, /试点必需项/);
  assert.match(briefMarkdown, /## 命令/);
  assert.match(briefMarkdown, /## 诊断链接/);
  assert.match(briefMarkdown, /npm run pilot:check/);
  const pilotLaunch = JSON.parse(fs.readFileSync(path.join(outputDir, "pilot-launch-summary.json"), "utf8"));
  assert.equal(pilotLaunch.decision, "GO_WITH_CAUTION");
  assert.equal(pilotLaunch.criteria.some((item) => item.key === "data_protection"), true);
  assert.match(fs.readFileSync(path.join(outputDir, "project-snapshot.md"), "utf8"), /项目快照/);
  assert.match(fs.readFileSync(path.join(outputDir, "risk-register.md"), "utf8"), /风险台账/);
  const issueReportMarkdown = fs.readFileSync(path.join(outputDir, "pilot-issue-report.md"), "utf8");
  assert.match(issueReportMarkdown, /内部试点问题上报模板/);
  assert.match(issueReportMarkdown, /页面顶部错误提示中的请求 ID/);
  assert.match(issueReportMarkdown, /S1：数据损坏/);
  assert.match(issueReportMarkdown, /\/ops\/summary/);
  assert.match(issueReportMarkdown, /是否已进入待办或风险台账/);
  const rollbackCardMarkdown = fs.readFileSync(path.join(outputDir, "pilot-rollback-card.md"), "utf8");
  assert.match(rollbackCardMarkdown, /内部试点回滚卡片/);
  assert.match(rollbackCardMarkdown, /npm run store:restore-backup/);
  assert.match(rollbackCardMarkdown, /\/storage\/doctor/);
  assert.match(rollbackCardMarkdown, /恢复来源：checkpoint 或 \.bak/);
  const deploymentDrillMarkdown = fs.readFileSync(path.join(outputDir, "pilot-deployment-drill.md"), "utf8");
  assert.match(deploymentDrillMarkdown, /内部试点部署演练清单/);
  assert.match(deploymentDrillMarkdown, /npm run start:lan/);
  assert.match(deploymentDrillMarkdown, /HARDWARE_FLOW_PILOT_ACCESS_CODE/);
  assert.match(deploymentDrillMarkdown, /JSON store/);
  assert.match(deploymentDrillMarkdown, /\/runtime\/network/);
  assert.match(deploymentDrillMarkdown, /pilot-rollback-card\.md/);
  const feedbackLedgerMarkdown = fs.readFileSync(path.join(outputDir, "pilot-feedback-ledger.md"), "utf8");
  assert.match(feedbackLedgerMarkdown, /内部试点反馈台账/);
  assert.match(feedbackLedgerMarkdown, /后续节点/);
  assert.match(feedbackLedgerMarkdown, /M7/);
  assert.match(feedbackLedgerMarkdown, /P0/);
  assert.match(feedbackLedgerMarkdown, /OPEN/);
  const m7BacklogMarkdown = fs.readFileSync(path.join(outputDir, "pilot-m7-backlog.md"), "utf8");
  assert.match(m7BacklogMarkdown, /# M7 Backlog 计划模板/);
  assert.match(m7BacklogMarkdown, /## Ready 条件/);
  assert.match(m7BacklogMarkdown, /复测结果或截图/);
  assert.match(m7BacklogMarkdown, /\| Backlog ID \| 来源反馈编号 \| 标题 \| 优先级 \|/);
  const trialScopeMarkdown = fs.readFileSync(path.join(outputDir, "pilot-trial-scope.md"), "utf8");
  assert.match(trialScopeMarkdown, /内部试点范围与运行策略/);
  assert.match(trialScopeMarkdown, /4-8/);
  assert.match(trialScopeMarkdown, /JSON store/);
  assert.match(trialScopeMarkdown, /PostgreSQL/);
  assert.match(trialScopeMarkdown, /项目经理/);
  const opsAlertsMarkdown = fs.readFileSync(path.join(outputDir, "pilot-ops-alerts.md"), "utf8");
  assert.match(opsAlertsMarkdown, /内部试点运维告警建议/);
  assert.match(opsAlertsMarkdown, /\/ops\/summary/);
  assert.match(opsAlertsMarkdown, /hardware_flow_http_5xx_total/);
  assert.match(opsAlertsMarkdown, /RUNTIME_PERSISTENCE/);
  assert.match(opsAlertsMarkdown, /S1/);
  const archiveIndexMarkdown = fs.readFileSync(path.join(outputDir, "pilot-archive-index.md"), "utf8");
  assert.match(archiveIndexMarkdown, /内部试点归档包总目录/);
  assert.match(archiveIndexMarkdown, /先看这几个/);
  assert.match(archiveIndexMarkdown, /pilot-trial-scope\.md/);
  assert.match(archiveIndexMarkdown, /pilot-deployment-drill\.md/);
  assert.match(archiveIndexMarkdown, /pilot-handoff-walkthrough\.md/);
  assert.match(archiveIndexMarkdown, /pilot-m6-closeout\.md/);
  assert.match(archiveIndexMarkdown, /pilot-test-plan\.md/);
  assert.match(archiveIndexMarkdown, /测试执行/);
  assert.match(archiveIndexMarkdown, /现场报错/);
  assert.match(archiveIndexMarkdown, /M6 收尾/);
  assert.match(archiveIndexMarkdown, /pilot-rollback-card\.md/);
  const handoffWalkthroughMarkdown = fs.readFileSync(path.join(outputDir, "pilot-handoff-walkthrough.md"), "utf8");
  assert.match(handoffWalkthroughMarkdown, /内部试点交接走查清单/);
  assert.match(handoffWalkthroughMarkdown, /打开归档包总目录/);
  assert.match(handoffWalkthroughMarkdown, /模拟现场报错/);
  assert.match(handoffWalkthroughMarkdown, /确认回滚路径/);
  assert.match(handoffWalkthroughMarkdown, /pilot-feedback-ledger\.md/);
  assert.match(handoffWalkthroughMarkdown, /走查主持人/);
  const m6CloseoutMarkdown = fs.readFileSync(path.join(outputDir, "pilot-m6-closeout.md"), "utf8");
  assert.match(m6CloseoutMarkdown, /M6 收尾判定/);
  assert.match(m6CloseoutMarkdown, /归档包完整/);
  assert.match(m6CloseoutMarkdown, /交接走查/);
  assert.match(m6CloseoutMarkdown, /回滚路径/);
  assert.match(m6CloseoutMarkdown, /内部试点的首批用户范围/);
  assert.match(m6CloseoutMarkdown, /PASS_WITH_NOTES/);
  const testPlanMarkdown = fs.readFileSync(path.join(outputDir, "pilot-test-plan.md"), "utf8");
  assert.match(testPlanMarkdown, /局域网试点测试方案/);
  assert.match(testPlanMarkdown, /TC-03 局域网启动/);
  assert.match(testPlanMarkdown, /TC-13 阶段门批准/);
  assert.match(testPlanMarkdown, /S1：数据损坏/);
  assert.match(testPlanMarkdown, /测试完成报告/);

  fs.rmSync(outputDir, { recursive: true, force: true });
});

test.after(() => {
  fs.rmSync(tempStoreDir, { recursive: true, force: true });
});
