function asArray(value) {
  return Array.isArray(value) ? value : [];
}

function json(value, fallback) {
  return value === undefined ? fallback : value;
}

export const postgresTableNames = [
  "projects",
  "phases",
  "gates",
  "role_pairs",
  "work_packages",
  "gate_requirements",
  "artifact_versions",
  "reviews",
  "risks",
  "agent_runs",
  "agent_findings",
  "work_package_evidence_refs",
  "gate_approval_packs",
  "notifications",
  "audit_events",
];

export function mapStoreToPostgresRows(store) {
  return {
    projects: asArray(store.projects).map((project) => ({
      id: project.id,
      name: project.name,
      product_line: project.productLine || null,
      owner_user_id: project.ownerUserId || "user-project-manager",
      current_phase_id: project.currentPhaseId || null,
      status: project.status,
      archived_at: project.archivedAt || null,
      archived_by_user_id: project.archivedByUserId || null,
      cloned_from_project_id: project.clonedFromProjectId || null,
      source_exported_at: project.sourceExportedAt || null,
      created_at: project.createdAt || null,
      updated_at: project.updatedAt || null,
    })),
    phases: asArray(store.phases).map((phase) => ({
      id: phase.id,
      project_id: phase.projectId,
      name: phase.name,
      sequence: phase.sequence,
      phase_key: phase.phaseKey || null,
      status: phase.status,
      starts_at: phase.startsAt || null,
      due_at: phase.dueAt || null,
    })),
    gates: asArray(store.gates).map((gate) => ({
      id: gate.id,
      project_id: gate.projectId,
      phase_id: gate.phaseId,
      name: gate.name,
      status: gate.status,
      approved_by_user_id: gate.approvedByUserId || null,
      approved_at: gate.approvedAt || null,
      approval_comment: gate.approvalComment || "",
    })),
    role_pairs: asArray(store.rolePairs).map((pair) => ({
      id: pair.id,
      project_id: pair.projectId,
      role_key: pair.roleKey,
      human_user_id: pair.humanUserId,
      agent_key: pair.agentKey,
      agent_permission_level: pair.agentPermissionLevel,
    })),
    work_packages: asArray(store.workPackages).map((workPackage) => ({
      id: workPackage.id,
      project_id: workPackage.projectId,
      phase_id: workPackage.phaseId,
      role_pair_id: workPackage.rolePairId,
      title: workPackage.title,
      required_artifact_type: workPackage.requiredArtifactType,
      artifact_template_key: workPackage.artifactTemplateKey || null,
      required_for_gate: workPackage.requiredForGate !== false,
      status: workPackage.status,
      due_at: workPackage.dueAt || null,
    })),
    gate_requirements: asArray(store.gateRequirements).map((requirement) => ({
      id: requirement.id,
      gate_id: requirement.gateId,
      work_package_id: requirement.workPackageId,
      required_artifact_type: requirement.requiredArtifactType,
    })),
    artifact_versions: asArray(store.artifactVersions).map((artifact) => ({
      id: artifact.id,
      work_package_id: artifact.workPackageId,
      artifact_type: artifact.artifactType,
      version: artifact.version,
      status: artifact.status,
      object_key: artifact.objectKey || null,
      content_json: json(artifact.content, {}),
      created_by_actor: artifact.createdByActor,
      created_at: artifact.createdAt || null,
    })),
    reviews: asArray(store.reviews).map((review) => ({
      id: review.id,
      work_package_id: review.workPackageId,
      reviewer_user_id: review.reviewerUserId,
      decision: review.decision,
      comment: review.comment || "",
      conditions: json(review.conditions, []),
      conditions_completed_at: review.conditionsCompletedAt || null,
      conditions_completed_by_user_id: review.conditionsCompletedByUserId || null,
      conditions_completion_comment: review.conditionsCompletionComment || "",
      reviewed_at: review.reviewedAt,
    })),
    risks: asArray(store.risks).map((risk) => ({
      id: risk.id,
      project_id: risk.projectId,
      phase_id: risk.phaseId,
      title: risk.title,
      severity: risk.severity,
      status: risk.status,
      owner_role_pair_id: risk.ownerRolePairId || null,
      mitigation: risk.mitigation || "",
      mitigation_owner_user_id: risk.mitigationOwnerUserId || null,
      mitigation_due_at: risk.mitigationDueAt || null,
      mitigation_status: risk.mitigationStatus || null,
      mitigation_updated_at: risk.mitigationUpdatedAt || null,
      mitigation_updated_by_user_id: risk.mitigationUpdatedByUserId || null,
      mitigation_completed_at: risk.mitigationCompletedAt || null,
      mitigation_completed_by_user_id: risk.mitigationCompletedByUserId || null,
      mitigation_completion_comment: risk.mitigationCompletionComment || "",
      accepted_by_user_id: risk.acceptedByUserId || null,
      accepted_at: risk.acceptedAt || null,
      accepted_comment: risk.acceptedComment || "",
      closed_by_user_id: risk.closedByUserId || null,
      closed_at: risk.closedAt || null,
      closed_comment: risk.closedComment || "",
      created_by_user_id: risk.createdByUserId || null,
      created_at: risk.createdAt || null,
    })),
    agent_runs: asArray(store.agentRuns).map((run) => ({
      id: run.id,
      work_package_id: run.workPackageId,
      agent_key: run.agentKey,
      status: run.status,
      input_refs: json(run.inputRefs, []),
      output_ref: run.outputRef || null,
      artifact_template_key: run.artifactTemplateKey || null,
      required_sections: json(run.requiredSections, []),
      required_review_roles: json(run.requiredReviewRoles, []),
      validation_json: run.validation || null,
      created_at: run.createdAt || null,
      completed_at: run.completedAt || null,
    })),
    agent_findings: asArray(store.agentFindings).map((finding) => ({
      id: finding.id,
      work_package_id: finding.workPackageId,
      agent_run_id: finding.agentRunId,
      severity: finding.severity,
      status: finding.status,
      message: finding.message,
      evidence_refs: json(finding.evidenceRefs, []),
    })),
    work_package_evidence_refs: asArray(store.evidenceRefs).map((ref) => ({
      id: ref.id,
      project_id: ref.projectId,
      work_package_id: ref.workPackageId,
      label: ref.label,
      ref: ref.ref,
      created_by_user_id: ref.createdByUserId,
      created_at: ref.createdAt,
    })),
    gate_approval_packs: asArray(store.gateApprovalPacks).map((pack) => ({
      id: pack.id,
      project_id: pack.projectId,
      gate_id: pack.gateId,
      phase_id: pack.phaseId,
      approved_by_user_id: pack.approvedByUserId,
      approved_at: pack.approvedAt,
      approval_comment: pack.approvalComment || "",
      review_pack_json: pack.reviewPack,
    })),
    notifications: asArray(store.notifications).map((notification) => ({
      id: notification.id,
      project_id: notification.projectId || null,
      user_id: notification.userId,
      title: notification.title,
      message: notification.message || "",
      type: notification.type,
      status: notification.status,
      object_type: notification.objectType || null,
      object_id: notification.objectId || null,
      created_at: notification.createdAt,
      read_at: notification.readAt || null,
    })),
    audit_events: asArray(store.auditEvents).map((event) => ({
      id: event.id,
      project_id: event.projectId || null,
      actor_type: event.actorType,
      actor_id: event.actorId,
      event_type: event.eventType,
      object_type: event.objectType,
      object_id: event.objectId,
      payload: json(event.payload, {}),
      created_at: event.createdAt,
    })),
  };
}
